SUB
SkyeEyks/Project-3-Group-16 pull request #12
Opened 2021-04-01 21:45 UTC by DrMpahleni

PULL

2021-04-03 11:20 UTC, SkyeEyks requested changes
No files added

2021-04-03 17:09 UTC, DrMpahleni commented
what's this?

________________________________
From: SkyeEyks ***@***.***>
Sent: 03 April 2021 12:20
To: SkyeEyks/Project-3-Group-16 ***@***.***>
Cc: Bongisa Mpahleni ***@***.***>; Author ***@***.***>
Subject: Re: [SkyeEyks/Project-3-Group-16] SUB (#12)


@SkyeEyks requested changes on this pull request.

No files added

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/SkyeEyks/Project-3-Group-16/pull/12#pullrequestreview-627450765>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATLAQCDKBG7KCJW264A5IZTTG32ZLANCNFSM42H3BOSQ>.

2021-04-03 17:31 UTC, SkyeEyks commented
> what's this?

You sent a pull request that had no files in it, and I don't think your code is in your main branch

2021-04-18 00:34 UTC, SkyeEyks approved these changes

2021-04-18 00:34 UTC, merged